[package]
name = "pi_store"
version = "0.1.0"
authors = ["zmythleo <zmythleo@gmail.com>"]
edition = "2018"

[dependencies]
parking_lot = "0.11"
futures = "0.3"
json = "0.11.13"
log = "0.4"
crc = "*"
bytes = "1.0"
lazy_static = "*"
fnv = "1.0.3"
tempdir = "0.3"
rand = "*"
crossbeam-channel = "0.5"
flume = "0.10"
hash_value = { path = "../pi_math/hash_value" }
bon = { path = "../pi_lib/bon" }
handler = { path = "../pi_lib/handler" }
atom = { path = "../pi_lib/atom" }
gray = {path = "../pi_lib/gray" }
guid = {path = "../pi_lib/guid" }
util = {path = "../pi_lib/util" }
sinfo = {path = "../pi_lib/sinfo" }
timer = {path = "../pi_lib/timer" }
ordmap = {path = "../pi_lib/ordmap" }
hash = { path = "../pi_lib/hash" }
async = { path = "../pi_lib/async" }
async_file = { path = "../pi_lib/async_file" }
async_transaction = { path = "../pi_lib/async_transaction" }
crc32fast = "1.2"
fastcmp = "1.0"
num_cpus = "1.13.0"