[package]
name = "pi_store"
version = "0.1.0"
authors = ["zmythleo <zmythleo@gmail.com>"]

[lib]

[dependencies]
bytes = "*"
lazy_static = "*"
pi_vm = { path = "../pi_vm" }
rocksdb = { path = "rust-rocksdb", version = "0.10.0" }
pi_db = {path = "../pi_db", version = "0.1.0"}
pi_lib = { path = "../pi_lib" }