[package]
name = "pi_store"
version = "0.11.2"
authors = ["vmos <vmosone007@gmail.com>"]
edition = "2021"
description = "File storage"
repository = "https://github.com/GaiaWorld/pi_store.git"
license = "MIT OR Apache-2.0"
keywords = ["pi", "file", "storage"]

[profile.test]
debug = true

[dependencies]
parking_lot = "0.12"
futures = "0.3"
log = "0.4"
bytes = "~1.11"
lazy_static = "1.5"
pi-async-rt = "0.5"
pi_async_file = "0.9"
pi_async_transaction = { version = "~0.12" }
async-lock = "3.0"
crossbeam-channel = "0.5"
dashmap = "6.2"
url = "2.5"
async-channel = "2.3"
pi_guid = "~0.1"
pi_hash = "0.1"
crc32fast = "~1.4"
fastcmp = "1.0"
quanta = "0.12"
pi_assets = "0.17"
pi_share = "0.6"
lzzzz = "~1.0"

[dev-dependencies]
pi_blocks_allocator = { path = "../pi_blocks_allocator" }
env_logger = "0.9"
rand = { version = "0.8", features = ["small_rng"] }
persy = "1.1"
lz4 = "~1.25"
redb = "~2.2"

[[bench]]
name = "wal_commit_contention"
harness = false
